### ISSUE TITLE
I assume you are starting with using git

### ISSUE THREAD

**Issue by CleanMachine1** [slashtechno/test#1]
Just saw this repo in my feed and it seems you are learning to use git and ssh

https://github.com/slashtechno.keys
thats my evidence for that.
However if you are beginning to learn git, you might find git-extras useful, its a package in repos, it has a lot of tools which are useful for easy use, although most of them are shorted versions of long commands

**Comment by CleanMachine1** [comment]
You also need to set your email address, since otherwise commits wont be yours. You can use your no reply and that will work

**Comment by CleanMachine1** [comment]
You should also learn to GPG sign your git commits to prove it is you

**Comment by slashtechno** [comment]
Hey @CleanMachine1, How do I set no-reply? 

> https://github.com/slashtechno.keys

Is this a security risk? Can someone edit my repos with that?

Sorry if it kept spamming you that I created a new repo btw

**Comment by CleanMachine1** [comment]
Nope, perfectly fine!
They are public keys, if you run cat ~.ssh/yourkey.pub you will see the same thing
Heres mine https://github.com/CleanMachine1.keys

And heres is Linus Torvalds https://github.com/Torvalds.keys

NEVER SHARE THE PRIVATE KEY!!! its the thing that identifies you, treat it like a password to your github

**Comment by CleanMachine1** [comment]
To set up private email thing.
Go here https://github.com/settings/emails then private your email so webbased commits don't reveal your email, then copy the githubnoreply then in a terminal run the following commands

`git config --global user.email 77907286+slashtechno@users.noreply.github.com`
then 
`git config --global user.name slashtechno`

Also consider setting up GPG signatures to prove that commits from you are ACTUALLY from you

https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key
it will take you 20 mins max, and it will give you a beautiful signed green tick on all commits
if you do that make sure to run the following command to autosign all commits
`git config --global commit.gpgsign true`

**Comment by slashtechno** [comment]
@CleanMachine1  Thank you so much. Also, like my octocat? 

I am trying to implement a git push feature in [this repo](https://github.com/slashtechno/push).

**Comment by CleanMachine1** [comment]
I don't really see the point of the repo, what does it do?

And for your profile picture, https://duckduckgo.com/?q=im+blue

**Comment by CleanMachine1** [comment]
Do you plan on learning to GPG?

**Comment by CleanMachine1** [comment]
Also feel free to contact me at gitter rather than a random test repo :)

**Comment by slashtechno** [comment]
@CleanMachine1 The point of the repo is to simplify pushing code (websites specifically) to a remote server. I made the program after I wanted to deploy a website to my Raspberry Pi running Apache. A couple days ago I added git push to.  As for GPG signing, I am not sure yet

**Comment by CleanMachine1** [comment]
Ok, still don't really know what it does :smile: 
And as for GPG signing, there is no reason not to

**Comment by slashtechno** [comment]
@CleanMachine1 I'm learning how to use GPG, and have set up commit signing.
Commit d9adadf98cdc315cff78a07b7e0c26be18162333 is signed
![image](https://user-images.githubusercontent.com/77907286/195221781-5a080e65-18b9-479d-8ae7-6a352c316c5c.png)

**Comment by CleanMachine1** [comment]
Cool!
